### ISSUE TITLE
[FEAT/fc002a/leeyc] 에러패스 기능 API 연결 

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#110]
## 💡 Feature Issue

- **이슈 제목**: 에러패스 기능 API 연결 
- **요약**: 에러패스 기능을 위해 선택된 에러패스 가능 재료를 API를 통해 전달하고, 백앤드 동작 확인 
- **기능 설명**: 에러패스된 재료를 보내 정상재로 변환하고, DB 업데이트를 확인한다. 
- **배경 및 맥락**: 에러패스 기능 1차 구현 

## 🌿  To-do

- [x] 체크박스로 에러패스할 재료 정보 받기
- [x] 에러패스 버튼 이벤트 추가
- [x] 에러패스 정보를 API를 통해 전달

## 📅 Timeline

- **시작일**: 2024-09-09
- **종료일**: 2024-09-11
- **마일스톤 이름**: 에러패스 기능 API 연결 
    - **목표**: 에러패스로 체크한 재료를 정상재로 업데이트하기
    - **기한**: 2024-09-12
    - **관련 이슈**: 106

## 🧩 Dependencies

- [x] #106 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
