### ISSUE TITLE
[FEAT/fs002/ash] 스케줄 편성 관리 API 연결 및 그래프 기능 구현

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-frontend#123]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 편성 관리 API 연결 및 그래프 기능 구현
- **요약**: 스케줄 편성 관리화면의 API 연결, 그래프 상세 기능 구현
- **기능 설명**: 스케줄 편성 관리 API 연결 동작, 그래프와 표 기능 구현
- **배경 및 맥락**: API을 통한 백엔드 통신 확인

## 🌿  To-do

- [ ] API 연결 dropdown 리스트 불러오기
- [ ] API로 표 불러오기
- [ ] 그래프와 불러온 값들 연결
- [ ] 그래프 세부 요소(클릭시 정보, width-thickness) 구현

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

- [ ] 

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
