### ISSUE TITLE
[FEAT/fs003/ash] 스케줄 결과 화면 API 연결

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-frontend#131]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 결과 화면 API 연결
- **요약**: 스케줄 결과 화면 API 연결
- **기능 설명**: 스케줄 결과 화면 API 연결
- **배경 및 맥락**: 스케줄 결과 화면 API 연결

## 🌿  To-do

- [ ] API 연결 dropdown 리스트 불러오기
- [ ] API 연결 결과 표로 불러오기
- [ ] 불러 온 값들을 그래프와 연결

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

- [ ] Dependency 1
- [ ] Dependency 2

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
