### ISSUE TITLE
[FEAT/schedule/ash] 스케줄 결과, 이력 화면 API 연결 및 웹소켓 연결

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-frontend#135]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 결과, 이력 화면 API 연결
- **요약**: 스케줄 결과, 이력 화면 API 연결 및 웹소켓 연결
- **기능 설명**: 스케줄 결과, 이력 화면 API 연결 및 웹소켓 연결
- **배경 및 맥락**: 스케줄 결과, 이력 화면 API 연결 및 웹소켓 연결

## 🌿  To-do

- [ ] 공정명과 날짜를 통한 API 요청
- [ ] 그래프 조정
- [ ] 받은 데이터 표로 보여주기
- [ ] css 조정
- [ ] WebSocket 통신 코드 추가
- [ ] 결과 화면 refactoring
- [ ] 추가) 데이터 없더라도 동작하는 코드 넣기

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
