### ISSUE TITLE
[FEAT/develop/leeyc] 에러패스 추천 기능 보완 

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#138]
## 💡 Feature Issue

- **이슈 제목**: 에러패스 추천 기능 보완 
- **요약**: 기존에 1차적으로 구현한 코드에서 수정되어야 할 부분 보완 + 상태관리, URL 등
- **기능 설명**: 기존 기능과 변경 없음
- **배경 및 맥락**: 에러패스 추천 기능을 완성하기! 

## 🌿  To-do

- [x] 상태 관리 수정
- [x] API 요청 부분 보완
- [x] 그 이외 필요한 부분은 진행하면서 해보기 

## 📅 Timeline

- **시작일**: 2024-09-26
- **종료일**: 2024-10-02
- **마일스톤 이름**: 에러패스 추천 기능 보완 
    - **목표**: 에러패스 추천 기능 완성하기 
    - **기한**: 2024-10-03
    - **관련 이슈**: 

## 🧩 Dependencies

- [x] #116 
- [x] #117 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
