### ISSUE TITLE
[FEAT/feedback/ash] 스케줄 편성 모달창 변경 및 다이렉트시 기본값 전달

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-frontend#151]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 편성 모달창 변경 및 다이렉트시 기본값 전달
- **요약**: 스케줄 편성 모달창 변경, 다이렉트시 기본값 전달, 모두 한글화
- **기능 설명**: 스케줄 편성 모달창 변경 - 편성/미편성 개수 표현 및 기준 표시, 다이렉트시 기본값 전달, 모두 한글화
- **배경 및 맥락**: 2024-10-04 멘토님 미팅에 의한 피드백 반영을 위한 브랜치

## 🌿  To-do

- [x] 스케줄 편성 모달창 변경 **
- [ ] 편성/미편성 개수 표현 및 기준 표시
- [ ] 다이렉트시 기본값 전달 및 화면 기본 세팅 구현
- [ ] 버튼, 표, 컴포넌트들 모두 한글화

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 🧩 Dependencies

- [ ] #135 

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
