### ISSUE TITLE
[Refactoring/control/leeyc] 관제 파트 프론트 전체 점검

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#157]
## 💡 Feature Issue

- **이슈 제목**:  관제 파트 프론트 전체 점검
- **요약**:  관제 파트 프론트 전체 점검
- **기능 설명**: 기능 수정 없고, UI 개선이나 코드 정리 등 리팩토링 진행
- **배경 및 맥락**: 마무리 

## 🌿  To-do

- [ ] 공통 env 파일에 맞게 수정 
- [ ] 코드 정리
- [ ] fc001a, fc002a UI 수정
- [ ] 그 이외에 필요한 부분 점검

## 📅 Timeline

- **시작일**: 2024-10-06
- **종료일**: 2024-10-09
- **마일스톤 이름**: 관제 파트 프론트 전체 점검
    - **목표**: 멘토님 피드백 반영 완료 및 관제파트 프론트 완료 
    - **기한**: 2024-10-09
    - **관련 이슈**:

## 🧩 Dependencies

- [ ] #147 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
