### ISSUE TITLE
[FEAT/FC-003/Pinky] 공장별 수급량 조회 화면

### ISSUE THREAD

**Issue by hanriverkitty** [POSTCO2024/postcoil-frontend#16]
## 💡 Feature Issue

- **이슈 제목**: 공장별 수급량 조회 화면
- **요약**: 공장별 수급량을 시각화하여 볼 수 있다

## 🌿  To-do

- [ ] 막대 차트 색상 고려
- [ ] 막대 차트 순서가 재고 많은 순으로 정렬
- [ ] 그림차트 디자인 고려

## 📅 Timeline

- **시작일**: 2024-08-14
- **종료일**: 2024-08-18
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: 차트 디자인과 상호작용까지 교려
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 👥 Assignees & Reviewers

- **할당자**: @hanriverkitty 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**: 없음
