### ISSUE TITLE
[Fix/control/leeyc] 프론트 에러 수정

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#176]
## 💡 Feature Issue

- **이슈 제목**: 프론트 에러 수정
- **요약**: 
- **기능 설명**: 
- **배경 및 맥락**: 

## 🌿  To-do

- [x] 생산 기한일 D-DAY 수정
- [x] 재료 진도 y값 
- [ ] fc003a 웹소켓 테스트 
- [ ] 그 외에 변경할 부분이 필요하면 수정

## 📅 Timeline

- **시작일**: YYYY-MM-DD
- **종료일**: YYYY-MM-DD
- **마일스톤 이름**:
    - **목표**: 프론트 최종 수정
    - **기한**: 2024-10-12
    - **관련 이슈**: 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
