### ISSUE TITLE
[setting/control/leeyc] 최종 버전에 맞게 수정

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#182]
## 💡 Feature Issue

- **이슈 제목**: 최종 버전에 맞게 수정
- **요약**: 최종 버전에 맞게 수정
- **기능 설명**: 관제 파트 시연용 화면 완성하기 
- **배경 및 맥락**: 최종발표 시연 준비 

## 🌿  To-do

- [ ] 작업시간 mock 데이터 수정
- [ ] 그래프 legend 수정 
- [ ] 그 이외의 수정 사항 반영

## 📅 Timeline

- **시작일**: 2024-10-11
- **종료일**: 2024-10-12
- **마일스톤 이름**: 시연용 화면 제작
    - **목표**: 시연용 화면 제작
    - **기한**: 2024-10-12
    - **관련 이슈**: 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
