### ISSUE TITLE
[FEAT/fs001/yerimee] 스케쥴 편성 화면

### ISSUE THREAD

**Issue by yerimee82** [POSTCO2024/postcoil-frontend#2]
## 💡 Feature Issue

- **이슈 제목**: 스케쥴 대상재 편성 화면
- **요약**:  스케쥴 편성을 위한 작업대상재 조회 화면입니다. 
                  
- **기능 설명**: 스케쥴 편성 화면에서 작업 대상재 및 제약조건, 우선순위를 확인할 수 있습니다. 
                         작업 대상재 클릭 시, 상세 정보를 확인할 수 있는 모달창을 구현합니다. 

## 🌿  To-do

- [ ] 대상재를 확인하는 표 만들기 
- [ ] 제약조건, 우선순위 확인 만들기
- [ ] 대상재 눌렀을 때, 모달창 구현 

## 📅 Timeline

- **시작일**: 2024-08-12
- **종료일**: 2024-08-19
- **마일스톤 이름**: (예시) 사용자 로그인 기능 완료
    - **목표**: (예시) 사용자가 이메일과 비밀번호로 로그인할 수 있도록 하는 기능 구현
    - **기한**: 2024-08-20
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 🧩 Dependencies

없음

## 👥 Assignees & Reviewers

- **할당자**: @yerimee82 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:
