### ISSUE TITLE
[FEAT/fc003a/leeyc] 공장 별 수급량 분석화면(추가) 구현

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#31]
## 💡 Feature Issue

- **이슈 제목**: 공장 별 수급량 분석화면 구현 
- **요약**: 공장(공정) 별 재료의 수급량을 비교할 수 있는 화면을 구현한다. 
- **기능 설명**: 각 공정의 작업 진행율과 생산기한을 표시한다. 
- **배경 및 맥락**: 멘토님과 미팅 후, 추가적으로 공장 별 수급량 분석화면을 추가하였다. 

## 🌿  To-do

- [x] 1차적으로 화면 구성
- [x] 구성한 화면 조정
- [ ] 컴포넌트 사용 가능하도록 리팩토링

## 📅 Timeline

- **시작일**: 2024-08-18
- **종료일**: 2024-08-20
- **마일스톤 이름**: 공장 별 수급량 분석화면 1차 완성
    - **목표**: 8/21 이전까지 1차적으로 화면 구성 및 간단한 css 화면 조정 마치기 
    - **기한**: 2024-08-20
    - **관련 이슈**: 29

## 🧩 Dependencies

- [x] #29

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn @hanriverkitty 

## 📌 Notes

- **참고 사항**: 없음
