### ISSUE TITLE
[FEAT/fs004/pinky] 스케줄이력 화면

### ISSUE THREAD

**Issue by hanriverkitty** [POSTCO2024/postcoil-frontend#39]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 이력 화면
- **요약**: 스케줄이력들이 나오고, 스케줄을 클릭하면 코일의 변경사항이 뜬다
- **기능 설명**: 스케줄이력들이 나오고, 스케줄을 클릭하면 코일의 변경사항이 색깔별로 뜬다
- **배경 및 맥락**: 

## 🌿  To-do

- [x] 스케줄이력화면
- [x] 스케줄 클릭시 스케줄에 배정된 롤단위별 코일들을 볼 수 있다
- [ ] 바뀐 코일들 색깔표시
- [ ] 스케줄 클릭시 롤 단위별 조회 화면으로 넘어갈때, Props로 스케줄 ID값을 전하는 방법 모색필요

## 📅 Timeline

- **시작일**: 2024-08-20
- **종료일**: 2024-08-20
- **마일스톤 이름**: 스케줄 이력화면
    - **목표**: 스케줄이력들이 나오고, 스케줄을 클릭하면 코일의 변경사항이 뜬다
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

- [ ] 
- [ ] 

## 👥 Assignees & Reviewers

- **할당자**: @hanriverkitty 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**:
