### ISSUE TITLE
[FEAT/fsm002/ash] 스케줄 기준 관리 화면

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/postcoil-frontend#4]
## 💡 Feature Issue

- **이슈 제목**: 스케줄 기준 관리 화면
- **요약**: 스케줄 기준 관리
- **기능 설명**: 제약조건, 미편성삽입조건 기준을 표로 표현, 조건 수정 및 추가 기능
- **배경 및 맥락**: 스케줄 편성시, 제약조건과 미편성삽입 조건에 대한 표를 표시하고, 이를 수정과 새로운 조건을 추가할 수 있게 해야한다.

## 🌿  To-do

- [x] 공정선택 select문
- [x] Rol단위 select문
- [x] 조회 버튼
- [x] 미편성삽입조건 표
- [x] 제약조건 표
- [x] 미편성삽입조건 수정, 추가 버튼
- [x] 제약조건 수정, 추가 버튼
- [x] 조건을 수정, 추가하는 모달창

## 📅 Timeline

- **시작일**: 2024-08-07
- **종료일**: 2024-08-15
- **마일스톤 이름**: 스케줄 기준 관리 화면 개발
    - **목표**: 스케줄 제약조건, 미편성삽입 기준 관리 화면 개발
    - **기한**: 2024-08-20
    - **관련 이슈**: 

## 🧩 Dependencies

없음

## 👥 Assignees & Reviewers

- **할당자**: @sohyun-ahn 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**: 모달창 포함
