### ISSUE TITLE
[FEAT/fc004a/leeyc] 공정 별 작업 대상재 대시보드 수정 

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#50]
## 💡 Feature Issue

- **이슈 제목**: 공정 별 작업 대상재 대시보드 수정 
- **요약**: 공정 별 작업 대상재 대시보드의 그래프를 추가 및 수정한다. 
- **기능 설명**: 생산 마감일이 임박한 재료에 대한 시각화 자료를 추가 하고, 그래프 구성을 수정한다.
- **배경 및 맥락**: 멘토님과의 미팅 이후 피드백을 반영 

## 🌿  To-do

- [x] 생산 마감일이 얼마 남지 않은 재료들을 알 수 있는 시각화 자료 추가
- [x] 해당 그래프 추가 후, 기존 그래프 병합(재료 정보를 병합할 예정)
- [x] 그래프 구성 완료 후, 위치 재배치

## 📅 Timeline

- **시작일**: 2024-08-22
- **종료일**: 2024-08-25
- **마일스톤 이름**: 공정 별 작업 대상재 대시보드 수정 
    - **목표**: 그래프 추가 및 재배치
    - **기한**: 2024-08-25
    - **관련 이슈**: 32

## 🧩 Dependencies

- [x] #32

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn @hanriverkitty 

## 📌 Notes

- **참고 사항**: 없음
