### ISSUE TITLE
[FEAT/fc002a/leeyc] 에러재 조회 화면

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#6]
## 💡 Feature Issue

- **이슈 제목**: 에러재 조회 화면
- **요약**: 에러재 및 대상재 조회 및 에러패스 
- **기능 설명**: 에러 기준에 맞게 에러재를 추출한 리스트를 조회하고, 에러재 중 대상재에 포함될 수 있는 경우, 에러패스를 수동으로 처리해준다. 에러패스된 재료는 정상재로 들어가 조회가능하다. 
- **배경 및 맥락**: 추출된 작업 대상재에서 에러재를 필터링 하는 화면이 필요

## 🌿  To-do

- [x] 공정 별 에러재 리스트 조회
- [x] 공정 별 대상재 리스트 조회
- [x] 검색 기준으로 검색
- [x] 에러패스 기능

## 📅 Timeline

- **시작일**: 2024-08-12
- **종료일**: 2024-08-14
- **마일스톤 이름**: 에러재 리스트 조회 및 에러패스 화면 기능 화면
    - **목표**: 에러재 리스트 조회 및 에러패스 화면 기능 완료
    - **기한**: 2024-08-14
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 🧩 Dependencies

- [ ] 
- [ ] 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @hanriverkitty 

## 📌 Notes

- **참고 사항**:
