### ISSUE TITLE
[FEAT/Mock데이터반영/leeyc] 관제 파트 조회화면 데이터셋 반영

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#67]
## 💡 Feature Issue

- **이슈 제목**: 관제 파트 리스트 조회 항목 Mock 데이터 셋 반영
- **요약**: 작업대상재 추출 화면(fc001a), 에러재 추출화면(fc002a)의 리스트 결과를 컬럼을 구성하여 보여줄 것 
- **기능 설명**: 기능은 변경 없음
- **배경 및 맥락**: 현재, 임의 데이터로 채워진 값을 Mock데이터로 변경한다. 중간 발표까지 보여줄 컬럼을 결정 및 반영해야한다. 

## 🌿  To-do

- [ ] 작업 대상재 추출 화면 데이터셋 변경
- [x] 에러재 추출 화면 데이터셋 변경
- [x] 테이블 UI 조정

## 📅 Timeline

- **시작일**: 2024-08-23
- **종료일**: 2024-08-24
- **마일스톤 이름**: Mock 데이터 반영하기 
    - **목표**: 리스트 조회 시, Mock 데이터를 반환하도록 수정하고, 테이블 UI 조정하기
    - **기한**: 2024-08-24
    - **관련 이슈**: 46, 62 

## 🧩 Dependencies

- [ ] #46
- [x] #62

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @sohyun-ahn 

## 📌 Notes

- **참고 사항**: 없음
