### ISSUE TITLE
[FEAT/common/leeyc] 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by dudco0040** [POSTCO2024/postcoil-frontend#7]
## 💡 Feature Issue

- **이슈 제목**: 공통 컴포넌트 구현
- **요약**: 공통 컴포넌트 기능 보완
- **기능 설명**: 공통적으로 사용되는 컴포넌트의 기능 구현 
- **배경 및 맥락**: 1차적으로 구현한 컴포넌트 코드를 보완하기 위한 작업

## 🌿  To-do

- [ ] Config 파일로 분리
- [ ] props 전달받는 부분 수정
- [ ] 체크박스 사용 여부 변경 

## 📅 Timeline

- **시작일**: 2024-08-11
- **종료일**: 2024-08-15
- **마일스톤 이름**: 공통 컴포넌트 피드백 반영 및 기능 보완 완료 
    - **목표**: 구조와 사용 편의성을 고려하여 코드 수정
    - **기한**: 2024-08-15
    - **관련 이슈**: #15, #18, #22 (추가되면 추후 수정 바람)

## 🧩 Dependencies

- [ ] 
- [ ] 

## 👥 Assignees & Reviewers

- **할당자**: @dudco0040 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**:

**Comment by dudco0040** [comment]
common2로 브런치 변경 후, merge 완료
